### ISSUE TITLE
DipUI doesn't build from Carthage on XCode 8

### ISSUE THREAD

**Issue by shuvaev** [AliSoftware/Dip-UI#16]
I've tried in Swift 3.0 project.
"Use Legacy Swift Language version" set to NO

Cartfile:
github "AliSoftware/Dip-UI"

Build log:
/usr/bin/xcrun xcodebuild -project /Users/Stan/tmp/DipUUUI/Carthage/Checkouts/Dip-UI/DipUI/DipUI.xcodeproj -scheme DipUI-iOS -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean buildBuild settings from command line:
    BITCODE_GENERATION_MODE = bitcode
    CARTHAGE = YES
    CODE_SIGN_IDENTITY =
    CODE_SIGNING_REQUIRED = NO
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = iphoneos10.0

=== CLEAN TARGET DipUI-iOS OF PROJECT DipUI WITH CONFIGURATION Release ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

=== BUILD TARGET DipUI-iOS OF PROJECT DipUI WITH CONFIGURATION Release ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

Command line build output:
carthage update --platform iOS
**\* Fetching Dip-UI
**\* Fetching Dip
**\* Downloading Dip.framework binary at "4.6.1"
**\* Checking out Dip-UI at "0.2.2"
**\* xcodebuild output can be found in /var/folders/q1/6l276hx53m590df28r4rvpv00000gn/T/carthage-xcodebuild.dvMvGI.log
**\* Building scheme "DipUI-iOS" in DipUI.xcodeproj
*\* CLEAN FAILED **

The following build commands failed:
    Check dependencies
(1 failure)
*\* BUILD FAILED **

The following build commands failed:
    Check dependencies
(1 failure)
A shell task (/usr/bin/xcrun xcodebuild -project /Users/Stan/tmp/DipUUUI/Carthage/Checkouts/Dip-UI/DipUI/DipUI.xcodeproj -scheme DipUI-iOS -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
*\* CLEAN FAILED **

The following build commands failed:
    Check dependencies
(1 failure)
*\* BUILD FAILED **

The following build commands failed:
    Check dependencies
(1 failure)

**Comment by ilyapuchka** [comment]
Swift 3 will be supported in release 1.0.0 (#15)

**Comment by ilyapuchka** [comment]
Fixed with #15 
Please check it on your side.

**Comment by shuvaev** [comment]
Now it works, thank you!
