### ISSUE TITLE
1.0.0 installation issue

### ISSUE THREAD

**Issue by JanBorowskiES** [AliSoftware/Dip-UI#17]
Hello,

I've noticed that new version of DipUI was released - "1.0.0", unfortunately I was unable to install it through CocoaPods. Version 0.2.2 pops up as latest. Has anyone experienced it?

BTW Thanks for this nice library.

**Comment by ilyapuchka** [comment]
Hi. I think there is some problem with pushing to trunk Swift 3 libs that depend on other Swift 3 libs cause they fail spec validation, so it is not pushed yet. But I didn't have time to investigate it deeper. I guess for now you can pin directly to master branch or 1.0.0 tag in your pod file. Building pods looks like working fine.

**Comment by ikesyo** [comment]
@ilyapuchka You might be missing `.swift-version` in the repo to use Swift 3 for a podspec linting.

**Comment by ilyapuchka** [comment]
Yeah, I think this is exactly what fixed it in Dip

**Comment by JanBorowskiES** [comment]
Thanks for quick response 👍
