### ISSUE TITLE
Setup travis integration

### ISSUE THREAD

**Issue by ilyapuchka** [AliSoftware/Dip-UI#2]
Travis lets setup only repos with administrative access, so I can not do that. I've added travis script, but you have to enable integration yourself, @AliSoftware

**Comment by AliSoftware** [comment]
Access added to travis, but the `.travis.yml` file [seems to fail to point to the proper Xcode project](https://travis-ci.org/AliSoftware/Dip-UI) :wink:

**Comment by AliSoftware** [comment]
I think that you could move everything up one level, to fit both for Travis, Carthage and SPM expectations
- `DipUI/DipUI` to `Sources`
- `DipUI/DipUI-Tests` to `UnitTests`
- `DipUI/DipUI.xcodeproj` to `DipUI.xcodeproj`

**Comment by ilyapuchka** [comment]
I've fixed that by pointing to the project in `xcodebuild`. I kept the sources layout identical to what we have in Dip.
