### ISSUE TITLE
Error: DependencyContainer has no member uiContainers, undeclared  type StoryboardInstantiabtable 

### ISSUE THREAD

**Issue by programmer-pragmatic** [AliSoftware/Dip-UI#26]
Hi,

I am following the tutorial, but somehow not getting it to work. Getting these two errors. I am able to jump to definitions to uiContainers and StoryboardInstantiatable, but compiler does not recognises any of the DependencyContainer.extensions and gives these errors.

Thanks In advance

**Comment by ilyapuchka** [comment]
Hi, @programmer-pragmatic. Please check that you have linked DipUI framework correctly. You can check out [VIPER-SWIFT](https://github.com/ilyapuchka/VIPER-SWIFT) example project for reference.

**Comment by programmer-pragmatic** [comment]
Thanks for the response!
Somehow I am able to make this program compile. I had to import DIP_UI. This was not mentioned to git page at https://github.com/AliSoftware/Dip-UI . Where as in viper example, it is still not compiling and giving errors. My solutions is compiling but I am still not able to resolve dependencies through storyboard which is really frustrating. We were in process on analysing dip for our project. After this experience, we are not sure about integrating DIP-UI. We would only integrate DIP only.
