### ISSUE TITLE
Strange behavior with several uiContainers

### ISSUE THREAD

**Issue by abesmon** [AliSoftware/Dip-UI#32]
Hi! In our project we wanted to use different uiContainers for different userStories, but we stuck in some sort of issue.

what happened:
at first we were using one uiContainer and it works like a charm 👍 

but then, as we added second container, some stage things start to appear

WE've added second container like
`DependencyContainer.uiContainers.append(storyBoardContainer)`

btw, first uiContainer was added just like this too.

And then, when controllers from new user story must be initialized, console wrote smth like

> No definition registered for type: HotelSearchVC, arguments: (), tag: nil.
> Check the tag, type you try to resolve, number, order and types of runtime arguments passed to `resolve()` and match them with registered factories for type HotelSearchVC.

BUT! though it wrote this in console, it also resolves injected properties like it was made to.

Then, we tried to use containers like in Readme
`DependencyContainer.uiContainers = [storyBoardContainer]`

and it starts working like it should.

So, the question is:
- Is uiContainers can't work with several containers? Or is there something that we're doing wrong?

**Comment by ilyapuchka** [comment]
Hi, @abesmon
Don't worry, injection works, as you can confirm, the error is being printed out just because we are looping through all ui containers trying to resolve requested type, but it's registered only in one. The error actually comes from Dip.
