### ISSUE TITLE
Example Project

### ISSUE THREAD

**Issue by max-potapov** [AliSoftware/Dip-UI#4]
Could you provide any working example project?

I've made some one based on README and it seems it doesn't work as expected – my dependencies won't be resolved in sample controller.

Here is a code:
https://github.com/max-potapov/Playground/tree/dip

**Comment by ilyapuchka** [comment]
Hi, Max. 
The issue in your example is that at the point when `application(_:didFinishLaunchingWithOptions:)` is called the view controller is already instantiated. You can check that by inspecting `application.windowns.first!.rootViewController`.
Put `DependencyContainer.uiContainer = container` line inside container configuration block and everything will work.
Thanks for pointing this out, I will reflect that in the README.
