### ISSUE TITLE
How to resolve UIViewController with runtime arguments?

### ISSUE THREAD

**Issue by Narayane** [AliSoftware/Dip-UI#44]
Hi,

I need to resolve a UIViewController with runtime arguments to do something like this following:

`container.register(.unique) { (id: String, object: MyProtocol?) in try MyViewModel(repository: container.resolve(), id: id, object: object) as MyViewModelProtocol }`

`container.register(storyboardType: MyUIViewController.self, tag: "MyTag")
            .resolvingProperties { container, vc in
                vc.viewModel = try container.resolve(arguments: id, object) as MyViewModelProtocol
}`

Is it possible?

Thanks.

**Comment by ilyapuchka** [comment]
duplicate https://github.com/AliSoftware/Dip/issues/192
